# Generated by Django 4.1.5 on 2023-01-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_feedback_serivce'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=400)),
                ('address2', models.CharField(max_length=400)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=500)),
                ('time', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='time',
        ),
    ]
