# Generated by Django 4.1.5 on 2023-01-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_information_remove_feedback_address1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('logo', models.CharField(max_length=400)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Serivce',
        ),
    ]
